# email_builder.py
# FINAL VERSION — manual + daily email identical layout

from datetime import datetime

# Color badges — identical to daily reminder mail
PRIORITY_COLORS = {
    "high": "#e63946",
    "medium": "#ff9f1c",
    "low": "#2a9d8f",
    "vendor_pending": "#9d4edd",
    "quotation_received": "#4361ee",
    "client_clarifications": "#3a86ff",
    "post_offer_queries": "#bc6c25",
    "overdue": "#6d6875",
}

CATEGORY_TITLES = {
    "high": "High Priority",
    "medium": "Medium Priority",
    "low": "Low Priority",
    "vendor_pending": "Vendors Not Responded",
    "quotation_received": "Quotation Received",
    "client_clarifications": "Client Clarifications",
    "post_offer_queries": "Post-Offer Client Queries",
    "overdue": "Overdue RFQs",
}


def make_summary_box(summary):
    """Top summary statistics identical to daily reminder."""
    rows = []
    for key in [
        "high", "medium", "low",
        "vendor_pending", "quotation_received",
        "client_clarifications", "post_offer_queries",
        "overdue"
    ]:
        count = summary.get(key, 0)
        color = PRIORITY_COLORS[key]
        label = CATEGORY_TITLES[key]
        rows.append(
            f"""
            <tr>
                <td style="padding:6px 0; font-size:15px;">
                    <span style="display:inline-flex; align-items:center;">
                        <span style="width:12px;height:12px;border-radius:50%;background:{color};display:inline-block;margin-right:8px;"></span>
                        {label}: <b>{count}</b>
                    </span>
                </td>
            </tr>
            """
        )

    return f"""
    <table style="width:100%;border-collapse:collapse;margin-top:5px;">
        {''.join(rows)}
    </table>
    """


def make_table_section(title, rows_list):
    """Render category table exactly the same as daily reminder."""
    if not rows_list:
        return ""

    color = None
    # find matching category color
    for k, v in CATEGORY_TITLES.items():
        if v == title:
            color = PRIORITY_COLORS[k]

    table_rows = ""
    for r in rows_list:
        table_rows += f"""
        <tr>
            <td style="padding:8px;border:1px solid #ddd;">{r.get('rfq_no','')}</td>
            <td style="padding:8px;border:1px solid #ddd;">{r.get('uid_no','')}</td>
            <td style="padding:8px;border:1px solid #ddd;">{r.get('customer','')}</td>
            <td style="padding:8px;border:1px solid #ddd;">{r.get('due_date','')}</td>
            <td style="padding:8px;border:1px solid #ddd;">{r.get('days_overdue','')}</td>
            <td style="padding:8px;border:1px solid #ddd;">{r.get('next_step','')}</td>
        </tr>
        """

    return f"""
    <h3 style="margin-top:30px;margin-bottom:10px;color:{color};font-size:20px;">
        ● {title}
    </h3>

    <table style="width:100%;border-collapse:collapse;margin-bottom:20px;font-size:15px;">
        <thead>
            <tr style="background:#f1f1f1;">
                <th style="padding:8px;border:1px solid #ddd;">RFQ No</th>
                <th style="padding:8px;border:1px solid #ddd;">UID No</th>
                <th style="padding:8px;border:1px solid #ddd;">Customer</th>
                <th style="padding:8px;border:1px solid #ddd;">Due Date</th>
                <th style="padding:8px;border:1px solid #ddd;">Days Overdue</th>
                <th style="padding:8px;border:1px solid #ddd;">Next Step</th>
            </tr>
        </thead>
        <tbody>
            {table_rows}
        </tbody>
    </table>
    """


def build_email_html(summary, sections):
    """MASTER TEMPLATE — manual + daily reminder both use this."""

    today = datetime.now().strftime("%d-%b-%Y (Friday)")

    html = f"""
    <div style="font-family:Arial, sans-serif;max-width:1100px;margin:auto;padding:20px;color:#333;">

        <h2 style="text-align:center;margin-bottom:10px;">
            <b>Daily RFQ Reminder (Level-50 Smart Assistant)</b>
        </h2>

        <h3 style="text-align:center;margin-top:0;margin-bottom:25px;font-weight:normal;">
            {today}
        </h3>

        <h2 style="margin-top:10px;margin-bottom:0;">Daily RFQ Summary</h2>

        <p style="margin:0;font-size:15px;">Total RFQs in Reminder: <b>{summary.get("total", "N/A")}</b></p>

        {make_summary_box(summary)}
        <hr style="margin:25px 0;border:none;border-top:1px solid #ccc;">
    """

    # Render all sections in EXACT daily ordering
    for key in [
        "high", "medium", "low",
        "vendor_pending", "quotation_received",
        "client_clarifications", "post_offer_queries",
        "overdue"
    ]:
        rows_list = sections.get(key, [])
        html += make_table_section(CATEGORY_TITLES[key], rows_list)

    html += """
        <br><br>
        <p style="text-align:center;font-size:13px;color:#666;">
            This automated reminder is generated by the Level-50 Smart RFQ Assistant.
        </p>
    </div>
    """

    return html
