# email_sender.py
import os
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

# ---------------------------------------------------------
# Build Email HTML Template
# ---------------------------------------------------------

def build_email_html(email_content):
    color_map = {
        "HIGH": "#ff4d4d",
        "MEDIUM": "#ffb84d",
        "LOW": "#5cb85c",
        "OVERDUE": "#cc0000",
        "VENDOR_PENDING": "#ff6600",
        "CLARIFICATION": "#0073e6",
        "QUOTATION_RECEIVED": "#4d79ff",
        "INVALID": "#999999",
        "ERROR": "#990000"
    }

    table_rows = ""
    for item in email_content:
        status = item.get("status", "")
        rfq = item.get("rfq", "")
        client = item.get("client", "")
        due = item.get("due", "")

        color = color_map.get(status, "#666666")

        table_rows += f"""
        <tr>
            <td style="padding: 6px 10px; border-bottom: 1px solid #ddd;">{rfq}</td>
            <td style="padding: 6px 10px; border-bottom: 1px solid #ddd;">{client}</td>
            <td style="padding: 6px 10px; border-bottom: 1px solid #ddd; font-weight:bold; color:{color};">
                {status}
            </td>
            <td style="padding: 6px 10px; border-bottom: 1px solid #ddd;">{due}</td>
        </tr>
        """

    html = f"""
    <html>
    <body style="font-family: Arial, sans-serif; background:#f6f6f6; padding:20px;">
        <div style="max-width:650px; margin:auto; background:white; padding:20px; border-radius:6px; box-shadow:0 0 5px rgba(0,0,0,0.1);">

            <h2 style="text-align:center; color:#333; margin-top:0;">
                📌 Level-50 RFQ Summary Report
            </h2>

            <p style="font-size:14px; color:#555;">
                Below is the latest RFQ update generated by your Level-50 automation system.
            </p>

            <table style="width:100%; border-collapse:collapse; margin-top:15px; font-size:14px;">
                <thead>
                    <tr style="background:#f0f0f0;">
                        <th style="padding:8px; border-bottom:2px solid #ccc; text-align:left;">RFQ No</th>
                        <th style="padding:8px; border-bottom:2px solid #ccc; text-align:left;">Client</th>
                        <th style="padding:8px; border-bottom:2px solid #ccc; text-align:left;">Status</th>
                        <th style="padding:8px; border-bottom:2px solid #ccc; text-align:left;">Due Days</th>
                    </tr>
                </thead>
                <tbody>
                    {table_rows}
                </tbody>
            </table>

            <p style="margin-top:25px; font-size:12px; color:#777; text-align:center;">
                This is an automated message sent by Level-50 System.<br>
                No manual action required.
            </p>
        </div>
    </body>
    </html>
    """

    return html


# ---------------------------------------------------------
# Send Email via SendGrid
# ---------------------------------------------------------

def send_email(email_content, recipients):
    """
    email_content = list from logic_engine
    recipients = comma-separated Emails from ENV
    """

    api_key = os.getenv("SENDGRID_API_KEY")
    sender = os.getenv("SENDGRID_FROM_EMAIL")

    if not api_key or not sender:
        raise RuntimeError("SendGrid API Key or Sender Email missing in environment variables.")

    html_body = build_email_html(email_content)

    message = Mail(
        from_email=sender,
        to_emails=[r.strip() for r in recipients.split(",")],
        subject="Level-50 RFQ Summary Report",
        html_content=html_body
    )

    try:
        sg = SendGridAPIClient(api_key)
        sg.send(message)
        return "email_sent"

    except Exception as e:
        print("SendGrid ERROR:", str(e))
        raise RuntimeError("Failed to send email via SendGrid")
