def build_email_content(sections):
    """
    Build final HTML email using the normalized sections
    generated by Level-50 Logic Engine.
    """

    html = """
    <html>
    <body>
        <h2>Daily RFQ Summary</h2>
    """

    for title, rows in sections.items():
        html += f"<h3>{title}</h3>"

        if not rows:
            html += "<p>No items.</p>"
            continue

        html += "<ul>"
        for row in rows:
            html += f"<li>{row}</li>"
        html += "</ul>"

    html += """
    </body>
    </html>
    """

    return html
